version: '3'

services:
  web:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "postgres:5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]
    volumes:
      - .:/app
    ports:
      - "8090:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pawcare_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: PawCare123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
