version: '3'

services:
  web:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "postgres:5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
