--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)
-- Dumped by pg_dump version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: pet_owners_petowner; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.pet_owners_petowner (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp without time zone,
    username character varying(150) NOT NULL,
    name character varying(100) NOT NULL,
    state character varying(200),
    city character varying(200),
    street character varying(200),
    phone_number character varying(15),
    email character varying(254),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_staff boolean DEFAULT false NOT NULL,
    is_superuser boolean NOT NULL
);


ALTER TABLE public.pet_owners_petowner OWNER TO admin;

--
-- Name: pet_owners_petowner_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.pet_owners_petowner_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pet_owners_petowner_id_seq OWNER TO admin;

--
-- Name: pet_owners_petowner_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.pet_owners_petowner_id_seq OWNED BY public.pet_owners_petowner.id;


--
-- Name: vets_vet; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.vets_vet (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    state character varying(200),
    city character varying(200),
    street character varying(200),
    "PLZ" integer,
    phone_number character varying(15),
    email character varying(254),
    created_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    last_login timestamp with time zone,
    password character varying(128) NOT NULL,
    username character varying(254) NOT NULL
);


ALTER TABLE public.vets_vet OWNER TO admin;

--
-- Name: vets_vet_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.vets_vet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vets_vet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pet_owners_petowner id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pet_owners_petowner ALTER COLUMN id SET DEFAULT nextval('public.pet_owners_petowner_id_seq'::regclass);


--
-- Data for Name: pet_owners_petowner; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.pet_owners_petowner (id, password, last_login, username, name, state, city, street, phone_number, email, created_at, is_active, is_staff, is_superuser) FROM stdin;
4	pbkdf2_sha256$720000$7qMz436PjOPnvs10NID3yF$Y1uh9xDML6q/5MUax0y5xbPWbjZuW2Zvt5tuuYaN70I=	2024-07-01 16:33:37.299828	salma		\N	\N	\N	\N	salma.karim@gmail.com	2024-07-01 16:32:42.49877	t	f	f
5	pbkdf2_sha256$720000$UbdtDyRejHaWr4dOSnVZXf$2Slz6a/BUNxtCu5yW88iUkxF2n/BX4Syq8uCPmNxNQY=	2024-07-01 22:55:03.832489	mahek.vora		\N	\N	\N	\N	mahek.vora@gmail.com	2024-07-01 22:54:50.811916	t	f	f
3	pbkdf2_sha256$720000$fj0wPBQFFOvbtqB6lzLUbH$WvvWRyqaspr1BsN83rxKYIUnT71K5fp5TfWLRKnmGEc=	2024-07-01 23:17:50.750354	lana		\N	\N	\N	\N	lanazamel74@gmail.com	2024-07-01 16:23:27.547605	t	f	f
\.


--
-- Data for Name: vets_vet; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.vets_vet (id, name, state, city, street, "PLZ", phone_number, email, created_at, is_active, is_staff, is_superuser, last_login, password, username) FROM stdin;
15	Tierarztpraxis Güttinger	Bayern	Schönau	Holz 1	84337	087269676725	info@tierarztpraxis-guettinger.de	2024-05-29 02:38:45.282279+02	t	f	f	\N	Tierarztpraxis@123	dr@tierarztpraxis-guettinger.de
14	Tierarztpraxis Stelzer	Bayern	Massing	Steinbüchl 58	84323	08724965550	info@tierarzt-massing.de	2024-05-29 02:38:01.088345+02	t	f	f	\N	Stelzer312	stelzer@tierarzt-massing.de
13	Tierarztpraxis Fritz	Bayern	Falkenberg	Hochstraße 9	84326	087279692995	\N	2024-05-29 02:37:16.836501+02	t	f	f	\N	fritz@123	fritz@tierarzt-fritz.de
12	Dr.med.vet. Alexander Horak Tierarzt	Bayern	Eggenfelden	Landshuter Str. 14	84307	087214320	\N	2024-05-29 02:35:47.881344+02	t	f	f	\N	alexander432	alexander.horak@horak-tierarzt.com
11	Tierarztpraxis Adigüzel	Bayern	Eggenfelden	Hofmark 5	84307	08721125575	tierarzt.adiguzel@t-online.de	2024-05-29 02:35:18.20308+02	t	f	f	\N	Praxis852Adigüzel	adiguzel@tierarztpraxis.de
10	Regina Eder Tierarzt	Bayern	Egglham	Hoibach 2	84385	085431525	\N	2024-05-29 02:34:34.852193+02	t	f	f	\N	Regina!34_	regina.eder@regina-tierarzt.de
9	Kleintierpraxis bei Anna	Bayern	Eggenfelden	Keferstraße 8	84307	015170182068	a.gozdzik@web.de	2024-05-29 02:21:48.343802+02	t	f	f	\N	a.gozdzik2354	a.gozdzik@web.de
8	Tierärztliche Gemeinschaftspraxis Schönau	Bayern	Schönau	Baron-Riederer-Straße 55	84337	087269409000	info@tieraerzte-sonnendorf.de	2024-05-29 02:20:44.181137+02	t	f	f	\N	Vets123654	dave@tieraerzte-sonnendorf.de
7	Dr. Wolfgang Deutsch Tierarzt	Bayern	Triftern	Graf-Lenberger-Straße 18	84371	085621310	\N	2024-05-29 02:19:16.649934+02	t	f	f	\N	Wolfgang_tierarzt	wolfgang@deutsch-tierarzt.de
6	Dr. Atanas Valko Tierarzt MVDr./VSV	Bayern	Pfarrkirchen	Weidenweg 2	84347	085613751	\N	2024-05-29 02:08:14.651681+02	t	f	f	\N	Atanas_tierarzt	atanas@atanas-valko.com
5	Kleintierpraxis Dr. Kerstin Deingruber	Bayern	Postmünster	Schalldorf 1	84389	08561988766	info@kleintierpraxis-pan.de	2024-05-29 01:07:19.168516+02	t	f	f	\N	kleintierpraxis-pan.de	kerstin@kleintierpraxis-pan.de
4	Dr.med.vet. Alfred Scheider Tierarzt	Bayern	Pfarrkirchen	Waldweg 17	84347	08561988767	\N	2024-05-29 01:05:19.802834+02	t	f	f	\N	Alfred1234	alfred@alfred-scheider.com
3	Andreas Hammerschmidt	Bayern	Pfarrkirchen	Innere Simbacher Str. 21	84347	0856171122	\N	2024-05-26 20:05:32.971046+02	t	f	f	\N	Tierarzt-andreas	andreas@andreas-tierarzt.de
17	Dr. Josef Beisl - Tierarzt	Bayern	Frontenhausen	Bahnhofstraße 75	84160	08732930093	praxis@tierarzt-frontenhausen.de	2024-05-29 02:43:40.016616+02	t	f	f	\N	Josefpraxis	praxis@tierarzt-frontenhausen.de
16	Burkhard Schleifer	Bayern	Wurmannsquick	Herzog-Stephan-Straße 12	84329	08725212	info@tierarztpraxis-schleifer.de	2024-05-29 02:39:47.639181+02	t	f	f	\N	Burkhard123	schleifer@tierarztpraxis-schleifer.de
29	Mahek Vora Tierarzt	\N	\N	\N	\N	\N	\N	2024-07-02 00:53:55.154175+02	t	f	f	2024-07-02 00:54:26.960426+02	pbkdf2_sha256$720000$WyA4XIbL7YC4j6hDso3U8q$XreQKq4BMptrnIonf2yui4mqmW10DL2/tRUg4vcW+Ik=	mahek.vora@gmail.com
28	Joumana Elsayed	\N	\N	\N	\N	\N	\N	2024-07-01 00:32:34.645624+02	t	f	f	2024-07-02 01:17:37.48927+02	pbkdf2_sha256$720000$TO4RWriGuua4mRDjGeJiyy$SdwlZ1QBzF5CkJrQSYyjAiMFH9iDJwieJRW9RWV/IQc=	joumanasalahedin@gmail.com
\.


--
-- Name: pet_owners_petowner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.pet_owners_petowner_id_seq', 5, true);


--
-- Name: vets_vet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.vets_vet_id_seq', 29, true);


--
-- Name: pet_owners_petowner pet_owners_petowner_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pet_owners_petowner
    ADD CONSTRAINT pet_owners_petowner_pkey PRIMARY KEY (id);


--
-- Name: pet_owners_petowner pet_owners_petowner_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.pet_owners_petowner
    ADD CONSTRAINT pet_owners_petowner_username_key UNIQUE (username);


--
-- Name: vets_vet vets_vet_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vets_vet
    ADD CONSTRAINT vets_vet_pkey PRIMARY KEY (id);


--
-- Name: vets_vet vets_vet_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vets_vet
    ADD CONSTRAINT vets_vet_username_key UNIQUE (username);


--
-- Name: vets_vet_username_fdce37b5_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX vets_vet_username_fdce37b5_like ON public.vets_vet USING btree (username varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

