# Generated by Django 5.0.4 on 2024-07-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pet_owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petowner',
            name='groups',
            field=models.ManyToManyField(related_name='pet_owners_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='petowner',
            name='user_permissions',
            field=models.ManyToManyField(related_name='pet_owners_user_permissions', to='auth.permission'),
        ),
    ]
