# Generated by Django 4.2 on 2024-07-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0009_alter_vet_user_permissions'),
        ('pet_owners', '0003_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vets.vet'),
        ),
    ]
