# Generated by Django 4.2 on 2024-07-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0004_pet_vet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='state',
        ),
    ]
