# Generated by Django 5.0.4 on 2024-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='PLZ',
            field=models.IntegerField(),
        ),
    ]
