# Generated by Django 5.0.4 on 2024-05-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_alter_vet_plz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='last_name',
        ),
    ]
