# Generated by Django 5.0.4 on 2024-05-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_rename_first_name_vet_name_remove_vet_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
