# Generated by Django 5.0.4 on 2024-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vets', '0004_alter_vet_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='groups',
            field=models.ManyToManyField(related_name='vet_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='vet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='vet',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='vet',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='user_permissions',
            field=models.ManyToManyField(related_name='vet_users', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='vet',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
