# Generated by Django 5.0.4 on 2024-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0005_vet_groups_vet_is_active_vet_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vet',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
