# Generated by Django 5.0.4 on 2024-06-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0006_alter_vet_password_alter_vet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='PLZ',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
