# Generated by Django 5.0.4 on 2024-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0007_alter_vet_plz_alter_vet_city_alter_vet_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
