# Generated by Django 5.0.4 on 2024-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vets', '0008_alter_vet_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='user_permissions',
            field=models.ManyToManyField(related_name='vet_user_permissions', to='auth.permission'),
        ),
    ]
