# Generated by Django 4.2 on 2024-07-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vets', '0009_alter_vet_user_permissions'),
        ('pet_owners', '0002_petowner_groups_petowner_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_owners.petowner')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vets.vet')),
            ],
        ),
    ]
