# Generated by Django 4.2 on 2024-07-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0003_pet'),
        ('vets', '0009_alter_vet_user_permissions'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('complaints', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_owners.petowner')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vets.vet')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
