# Generated by Django 4.2 on 2024-07-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recreation',
            name='address',
        ),
        migrations.AddField(
            model_name='recreation',
            name='PLZ',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
