# Generated by Django 4.2 on 2024-07-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0002_remove_recreation_address_recreation_plz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recreation',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recreation',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
