# Generated by Django 4.2 on 2024-07-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0003_alter_recreation_city_alter_recreation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreation',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
