# Generated by Django 4.2 on 2024-07-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0004_recreation_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
