# Generated by Django 4.2 on 2024-07-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0005_alter_recreation_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation',
            name='category',
            field=models.CharField(choices=[('trail', 'Dog Trail'), ('park', 'Dog Park'), ('grooming', 'Grooming Service'), ('boarding', 'Boarding House'), ('care', 'Day Care')], max_length=20),
        ),
    ]
