# Generated by Django 4.2 on 2024-07-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0006_alter_recreation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
